name: Chess

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: self-hosted
    timeout-minutes: 1440

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Preparations
        run: |
          #sudo apt update
          #sudo apt install -y git build-essential
          _ICCF=0 _NOEDIT=2 _CHESS960=0 sh build.sh
          chmod 0755 baeagn
      
      - name: Execution
        run: |
          GN=0
          LTG=25200
          PROCESSORS=3
          ulimit -t $LTG
          for n in $(seq 1 $PROCESSORS); do
            fisher=false sh dlpgn.sh $GN >$GN.txt
            ./baeagn >>$GN.txt 2>&1 &
            GN=$(($GN + 1))
          done
          wait
          GN=0
          for n in $(seq 1 $PROCESSORS); do
            cat $GN.txt
            GN=$(($GN + 1))
          done

