name: ICCF

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Preparations
        run: |
          sudo apt update
          sudo apt install -y git pgn-extract build-essential
      
      - name: Execution
        run: |
          mkdir -p anl
          ulimit -t 21000
          for gamesymbol in $(cat pgn/gamelist.txt); do
            cp -a pgn/$gamesymbol.pgn start.pgn
            export gamesymbol
            _ICCF=1 _NOEDIT=1 _CHESS960=0 sh build.sh
            sleep 5
            ./baeagn >anl/$gamesymbol.anl 2>&1 &
            sleep 5
          done
          wait
          for gamesymbol in $(cat pgn/gamelist.txt); do
            echo $gamesymbol
            cat anl/$gamesymbol.anl
          done

