name: Bench2

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Preparations
        run: |
          sudo apt update
          sudo apt install -y git pgn-extract build-essential
          _NOEDIT=1 _CHESS960=0 sh build.sh
      
      - name: Execution
        run: |
          ./baeagn 2>&1 &
          wait


