name: ICCF

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Preparations
        run: |
          sudo apt update
          sudo apt install -y git pgn-extract build-essential
          _NOEDIT=1 _CHESS960=0 sh build.sh
      
      - name: Execution
        run: |
          mkdir -p anl
          ulimit -t 1500
          for gamesymbol in $(cat pgn/gamelist.txt); do
            rm -rf start.pgn
            ln -sf pgn/$gamesymbol.pgn start.pgn
            ./baeagn >anl/$gamesymbol.anl 2>&1 &
          done
          wait
          for gamesymbol in $(cat pgn/gamelist.txt); do
            echo $gamesymbol
            cat anl/$gamesymbol.anl
          done

