name: Chess

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Preparations
        run: |
          sudo apt update
          sudo apt install -y git build-essential
          _NOEDIT=2 _CHESS960=0 sh build.sh
      
      - name: Execution
        run: |
          GN=0
          for n in $(seq 1 1); do
            LTG=43200
            fisher=false sh dlpgn.sh $GN >$GN.txt
            ulimit -t $LTG
            ./baeagn >>$GN.txt 2>&1 &
            GN=$(($GN + 1))
          done
          sleep $LTG
          GN=0
          for n in $(seq 1 1); do
            cat $GN.txt
            GN=$(($GN + 1))
          done

