name: Chess

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: self-hosted
    timeout-minutes: 28800
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Preparations
        run: |
          sudo apt update
          sudo apt install -y git pgn-extract build-essential
          _NOEDIT=1 _CHESS960=0 sh build.sh
          mv baeagn iccf
          _NOEDIT=2 _CHESS960=0 sh build.sh
          chmod 0755 baeagn iccf
      
      - name: Execution
        run: |
          GN=0
          LTG=333
          ulimit -t $LTG
          ./iccf >iccf.txt 2>&1 &
          for n in $(seq 1 17); do
            fisher=false sh dlpgn.sh $GN >$GN.txt
            ./baeagn >>$GN.txt 2>&1 &
            GN=$(($GN + 1))
          done
          wait
          GN=0
          cat iccf.txt
          for n in $(seq 1 17); do
            cat $GN.txt
            GN=$(($GN + 1))
          done

